development:
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  

test:
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  

production:
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
